export const schema = {
  created_at: 1666293218,
  default_sorting_field: 'rank',
  enable_nested_fields: false,
  fields: [
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'url',
      optional: false,
      sort: false,
      type: 'string',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'title',
      optional: true,
      sort: false,
      type: 'string',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'text',
      optional: true,
      sort: false,
      type: 'string',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'platform',
      optional: true,
      sort: false,
      type: 'string',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'tags',
      optional: true,
      sort: false,
      type: 'string[]',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'rank',
      optional: false,
      sort: true,
      type: 'float',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'type',
      optional: true,
      sort: false,
      type: 'string',
    },
    {
      facet: false,
      index: true,
      infix: false,
      locale: '',
      name: 'measure_text_length',
      optional: true,
      sort: true,
      type: 'int32',
    },
  ],
  name: 'knowledge',
  num_documents: 21090,
  symbols_to_index: [],
  token_separators: ['.', '/', '-', '_'],
}
